// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package douyinrelationservice

import (
	"context"

	"mini-douyin/service/message/rpc/message"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DouyinMessageChatRequest         = message.DouyinMessageChatRequest
	DouyinMessageChatResponse        = message.DouyinMessageChatResponse
	DouyinRelationActionRequest      = message.DouyinRelationActionRequest
	DouyinRelationActionResponse     = message.DouyinRelationActionResponse
	DouyinRelationFriendListRequest  = message.DouyinRelationFriendListRequest
	DouyinRelationFriendListResponse = message.DouyinRelationFriendListResponse
	FriendUser                       = message.FriendUser
	Message                          = message.Message
	User                             = message.User

	DouyinRelationService interface {
		FriendList(ctx context.Context, in *DouyinRelationFriendListRequest, opts ...grpc.CallOption) (*DouyinRelationFriendListResponse, error)
		Chat(ctx context.Context, in *DouyinMessageChatRequest, opts ...grpc.CallOption) (*DouyinMessageChatResponse, error)
		Action(ctx context.Context, in *DouyinRelationActionRequest, opts ...grpc.CallOption) (*DouyinRelationActionResponse, error)
	}

	defaultDouyinRelationService struct {
		cli zrpc.Client
	}
)

func NewDouyinRelationService(cli zrpc.Client) DouyinRelationService {
	return &defaultDouyinRelationService{
		cli: cli,
	}
}

func (m *defaultDouyinRelationService) FriendList(ctx context.Context, in *DouyinRelationFriendListRequest, opts ...grpc.CallOption) (*DouyinRelationFriendListResponse, error) {
	client := message.NewDouyinRelationServiceClient(m.cli.Conn())
	return client.FriendList(ctx, in, opts...)
}

func (m *defaultDouyinRelationService) Chat(ctx context.Context, in *DouyinMessageChatRequest, opts ...grpc.CallOption) (*DouyinMessageChatResponse, error) {
	client := message.NewDouyinRelationServiceClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}

func (m *defaultDouyinRelationService) Action(ctx context.Context, in *DouyinRelationActionRequest, opts ...grpc.CallOption) (*DouyinRelationActionResponse, error) {
	client := message.NewDouyinRelationServiceClient(m.cli.Conn())
	return client.Action(ctx, in, opts...)
}
