// Code generated by goctl. DO NOT EDIT.
package types

type Douyin_user_info struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	FollowCount     int64  `json:"follow_count,optional"`
	FollowerCount   int64  `json:"follower_count,optional"`
	IsFollow        bool   `json:"is_follow"`
	Avatar          string `json:"avatar,optional"`
	BackgroundImage string `json:"background_image,optional"`
	Signature       string `json:"signature,optional"`
	TotalFavorited  int64  `json:"total_favorited,optional"`
	WorkCount       int64  `json:"work_count,optional"`
	FavoriteCount   int64  `json:"favorite_count,optional"`
}

type Douyin_favorite_action_request struct {
	Token      string `form:"token"`
	VideoId    int64  `form:"video_id"`
	ActionType int32  `form:"action_type"`
}

type Douyin_favorite_action_response struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,optional"`
}

type Douyin_favorite_list_request struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type Douyin_favorite_list_response struct {
	StatusCode int32          `json:"status_code"`
	StatusMsg  string         `json:"status_msg,optional"`
	VideoList  []Douyin_video `json:"video_list"`
}

type Douyin_comment_action_request struct {
	Token       string `form:"token"`
	VideoId     int64  `form:"video_id"`
	ActionType  int32  `form:"action_type"`
	CommentText string `form:"comment_text,optional"`
	CommentId   int64  `form:"comment_id,optional"`
}

type Douyin_comment_action_response struct {
	StatusCode int32          `json:"status_code"`
	StatusMsg  string         `json:"status_msg,optional"`
	Comment    Douyin_comment `json:"comment,optional"`
}

type Douyin_comment_list_request struct {
	Token   string `form:"token"`
	VideoId int    `form:"video_id"`
}

type Douyin_comment_list_response struct {
	StatusCode  int              `json:"status_code"`
	StatusMsg   string           `json:"status_msg,optional"`
	CommentList []Douyin_comment `json:"comment_list"`
}

type Douyin_video struct {
	Id            int64            `json:"id"`
	Author        Douyin_user_info `json:"author"`
	PlayUrl       string           `json:"play_url"`
	CoverUrl      string           `json:"cover_url"`
	FavoriteCount int64            `json:"favorite_count"`
	CommentCount  int64            `json:"comment_count"`
	IsFavorite    bool             `json:"is_favorite"`
	Title         string           `json:"title"`
}

type Douyin_comment struct {
	Id         int64            `json:"id"`
	User       Douyin_user_info `json:"user"`
	Content    string           `json:"content"`
	CreateDate string           `json:"create_date"`
}

type Douyin_message_chat_request struct {
	Token      string `form:"token"`
	ToUserID   int64  `form:"to_user_id"`
	PreMsgTime int64  `form:"pre_msg_time"`
}

type Douyin_message_chat_response struct {
	StatusCode  int32            `json:"status_code"`
	StatusMsg   string           `json:"status_msg,optional"`
	MessageList []Douyin_message `json:"message_list"`
}

type Douyin_message struct {
	ID         int64  `json:"id"`
	ToUserID   int64  `json:"to_user_id"`
	FromUserID int64  `json:"from_user_id"`
	Content    string `json:"content"`
	CreateTime int64  `json:"create_time,optional"`
}

type Douyin_message_action_request struct {
	Token      string `form:"token"`
	ToUserID   int64  `form:"to_user_id"`
	ActionType int32  `form:"action_type"`
	Content    string `form:"content"`
}

type Douyin_message_action_response struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,optional"`
}

type Douyin_user_login_request struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type Douyin_user_login_response struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,optional"`
	UserID     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type Douyin_user_register_request struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type Douyin_user_register_response struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,optional"`
	UserID     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type Douyin_user_request struct {
	UserID int64  `form:"user_id"`
	Token  string `form:"token"`
}

type Douyin_user_response struct {
	StatusCode int32            `json:"status_code"`
	StatusMsg  string           `json:"status_msg,optional"`
	User       Douyin_user_info `json:"user"`
}

type Douyin_publish_action_request struct {
	Token string `form:"token"`
	Title string `form:"title"`
}

type Douyin_publish_action_response struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,optional"`
}

type Douyin_publish_list_request struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type Douyin_publish_list_response struct {
	StatusCode int32          `json:"status_code"`
	StatusMsg  string         `json:"status_msg"`
	VideoList  []Douyin_video `json:"video_list"`
}

type Douyin_feed_request struct {
	Token      string `form:"token,optional"`
	LatestTime int64  `form:"latest_time,optional"`
}

type Douyin_feed_response struct {
	StatusCode int32          `json:"status_code"`
	StatusMsg  string         `json:"status_msg,optional"`
	VideoList  []Douyin_video `json:"video_list"`
	NextTime   int64          `json:"next_time,optional"`
}

type Douyin_relation_action_request struct {
	Token      string `form:"token"`
	ToUserId   int64  `form:"to_user_id"`
	ActionType int32  `form:"action_type"`
}

type Douyin_relation_action_response struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,optional"`
}

type Douyin_relation_follow_list_request struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type Douyin_relation_follow_list_response struct {
	StatusCode int32              `json:"status_code"`
	StatusMsg  string             `json:"status_msg,optional"`
	UserList   []Douyin_user_info `json:"user_list"`
}

type Douyin_relation_follower_list_request struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type Douyin_relation_follower_list_response struct {
	StatusCode int32              `json:"status_code"`
	StatusMsg  string             `json:"status_msg,optional"`
	UserList   []Douyin_user_info `json:"user_list"`
}

type Douyin_relation_friend_list_request struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type Douyin_relation_friend_list_response struct {
	StatusCode int32                     `json:"status_code"`
	StatusMsg  string                    `json:"status_msg,optional"`
	UserList   []Douyin_friend_user_info `json:"user_list"`
}

type Douyin_friend_user_info struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	FollowCount     int64  `json:"follow_count,optional"`
	FollowerCount   int64  `json:"follower_count,optional"`
	IsFollow        bool   `json:"is_follow"`
	Avatar          string `json:"avatar,optional"`
	BackgroundImage string `json:"background_image,optional"`
	Signature       string `json:"signature,optional"`
	TotalFavorited  int64  `json:"total_favorited,optional"`
	WorkCount       int64  `json:"work_count,optional"`
	FavoriteCount   int64  `json:"favorite_count,optional"`
	Message         string `json:"message,optional"`
	MessageType     int64  `json:"message_type"`
}
