// Code generated by goctl. DO NOT EDIT.
// Source: interact.proto

package interactclient

import (
	"context"

	"mini-douyin/service/interact/rpc/interact"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment                      = interact.Comment
	DouyinCommentActionRequest   = interact.DouyinCommentActionRequest
	DouyinCommentActionResponse  = interact.DouyinCommentActionResponse
	DouyinCommentListRequest     = interact.DouyinCommentListRequest
	DouyinCommentListResponse    = interact.DouyinCommentListResponse
	DouyinFavoriteActionRequest  = interact.DouyinFavoriteActionRequest
	DouyinFavoriteActionResponse = interact.DouyinFavoriteActionResponse
	DouyinFavoriteListRequest    = interact.DouyinFavoriteListRequest
	DouyinFavoriteListResponse   = interact.DouyinFavoriteListResponse
	User                         = interact.User
	Video                        = interact.Video

	Interact interface {
		FavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...grpc.CallOption) (*DouyinFavoriteActionResponse, error)
		FavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, opts ...grpc.CallOption) (*DouyinFavoriteListResponse, error)
		CommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error)
		CommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error)
	}

	defaultInteract struct {
		cli zrpc.Client
	}
)

func NewInteract(cli zrpc.Client) Interact {
	return &defaultInteract{
		cli: cli,
	}
}

func (m *defaultInteract) FavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...grpc.CallOption) (*DouyinFavoriteActionResponse, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.FavoriteAction(ctx, in, opts...)
}

func (m *defaultInteract) FavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, opts ...grpc.CallOption) (*DouyinFavoriteListResponse, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.FavoriteList(ctx, in, opts...)
}

func (m *defaultInteract) CommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.CommentAction(ctx, in, opts...)
}

func (m *defaultInteract) CommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.CommentList(ctx, in, opts...)
}
