// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package server

import (
	"context"

	"mini-douyin/service/social/rpc/follow"
	"mini-douyin/service/social/rpc/internal/logic"
	"mini-douyin/service/social/rpc/internal/svc"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	follow.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServer) FollowAction(ctx context.Context, in *follow.DouyinRelationActionRequest) (*follow.DouyinRelationActionResponse, error) {
	l := logic.NewFollowActionLogic(ctx, s.svcCtx)
	return l.FollowAction(in)
}

func (s *FollowServer) FollowList(ctx context.Context, in *follow.DouyinRelationFollowListRequest) (*follow.DouyinRelationFollowListResponse, error) {
	l := logic.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}

func (s *FollowServer) FollowerList(ctx context.Context, in *follow.DouyinRelationFollowerListRequest) (*follow.DouyinRelationFollowerListResponse, error) {
	l := logic.NewFollowerListLogic(ctx, s.svcCtx)
	return l.FollowerList(in)
}
