// Code generated by goctl. DO NOT EDIT.
package types

type Duyin_publish_action_request struct {
	Token string `json:"token"`
	Data  byte   `json:"data"`
	Title string `json:"title"`
}

type Duyin_publish_action_response struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type Douyin_publish_list_request struct {
	LatestTime string `json:"latest_time"`
	Token      string `json:"token"`
}

type Douyin_publish_list_response struct {
	StatusCode int         `json:"status_code"`
	StatusMsg  string      `json:"status_msg"`
	NextTime   int         `json:"next_time"`
	VideoList  []VideoList `json:"video_list"`
}

type Douyin_feed_request struct {
	Token  string `json:"token"`
	UserID string `json:"user_id"`
}

type Douyin_feed_response struct {
	StatusCode int         `json:"status_code"`
	StatusMsg  string      `json:"status_msg"`
	VideoList  []VideoList `json:"video_list"`
}

type Author struct {
	ID            int    `json:"id"`
	Name          string `json:"name"`
	FollowCount   int    `json:"follow_count"`
	FollowerCount int    `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}

type VideoList struct {
	ID            int    `json:"id"`
	Author        Author `json:"author"`
	PlayURL       string `json:"play_url"`
	CoverURL      string `json:"cover_url"`
	FavoriteCount int    `json:"favorite_count"`
	CommentCount  int    `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	Title         string `json:"title"`
}
