// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mini-douyin/service/interact/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/favorite/action",
				Handler: FavoriteActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/favorite/list",
				Handler: FavoriteListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/comment/action",
				Handler: CommentActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/comment/list",
				Handler: CommentListHandler(serverCtx),
			},
		},
	)
}
